### ISSUE TITLE
go get: multiple-value uuid.NewV1() in single-value context

### ISSUE THREAD

**Issue by webextends** [CyCoreSystems/ari-proxy#17]
Hi, when I launch "go get" to install your proxy, I get these errors:

../../../ari/client/native/bridge.go:28: multiple-value uuid.NewV1() in single-value context
../../../ari/client/native/bridge.go:140: multiple-value uuid.NewV1() in single-value context
../../../ari/client/native/channel.go:92: multiple-value uuid.NewV1() in single-value context
../../../ari/client/native/channel.go:121: multiple-value uuid.NewV1() in single-value context
../../../ari/client/native/channel.go:343: multiple-value uuid.NewV1() in single-value context
../../../ari/client/native/client.go:89: multiple-value uuid.NewV1() in single-value context

Am I doing something wrong or is there any bug?
Is it just a notice message that I can ignore?
Thanks
Gabriele

**Comment by Ulexus** [comment]
I've been sitting on this one for a bit because it is going to be a breaking change for several of my deployments.  The problem is that the author of the `uuid` package released a new version which breaks the API, which is what you are seeing there.

You should be fine if you use [`glide`](http://glide.sh/) or the newer [`dep`](https://github.com/golang/dep) (which will read the glide constraint information), but the default current version of `uuid` is broken.

I'm going to have to find some time to coordinate this change and update; I just haven't yet figured out when and exactly how to do it.

**Comment by Ulexus** [comment]
Status update:  the latest tagged version (v1.2.0) now does not break the API.  `go get` on the dependency will still result in a breakage, so we are still in an a limbo.  If we upgrade to the new API, we would have to abandon the semantic versioning for that dependency.

Basically, until go.uuid releases v2.x, we are dead in the water.
