### ISSUE TITLE
Requests documentation

### ISSUE THREAD

**Issue by Tzomas** [CyCoreSystems/ari-proxy#30]
Hi all,

Before all, thanks for this project.
I'm trying to make a nodejs nats client for ari-proxy. But it's not clear to me which is the request format. I have not experience with go so it's really hard to understand how the nats request are made.
I tried to create, for example, a bridge with subject `ari.create.myapp.asteriskid`. But i'm not sure how the payload have to be send i try with:
```
{
  "type": "mixed"
}
```

```
{
  "Kind": "BridgeCreate",
  "Data": {
    "type": "mixed"
  }
}
```

```
{
  "Kind": "BridgeCreate",
  "BridgeCreate": {
    "type": "mixed"
  }
}
```

And more that I don't remember right now. Is there any doc or can you provide a example of payload for create a resource, as bridge or channel, and for example a delete, to see how id is passed to nats?

**Comment by Ulexus** [comment]
First, thanks for the attempt.  I've been meaning to get around to looking at implementing the client side of the proxy in Node for a while, but I just can't seem to motivate myself to going back to Node after all these years. :)

The structure is defined in [proxy.Request](https://pkg.go.dev/github.com/CyCoreSystems/ari-proxy/v5@v5.0.3/proxy?tab=doc#Request), and all of the protocol structures should be there.  This _mostly_ corresponds to your third option, above.   However, if you will note the json tags for each of the fields, you will see that each of them is translated into snake_case for JSON, since that is a bit more standard.  Thus, it would become:

```json
{
  "kind": "BridgeCreate",
  "bridge_create": {
    "type": "mixed"
  }
}
```

You can always run one of the examples with your NATS daemon running with trace enabled to see what is going across the line, if you need to do so.

**Comment by Ulexus** [comment]
BTW, I'm happy to implement some autogeneration for these structures in Node, if you come up with a template which would be helpful in that regard.

**Comment by Tzomas** [comment]
Thanks for your quick reply, that was what I missed, the proxy.Request. It works perfect now. When I get a functional client, I will share it.

thanks you again :D
